server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#      routes:
#        - id: test
#          uri: lb://eureka-client
#          predicates:
#          - Path=/main/test
#            Method=GET

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
